### ISSUE TITLE
Patches: Copied or Moved file changes don't show the possible diff

### ISSUE THREAD

**Issue by sebastinez** [cytechmobile/radicle-vscode-extension#100]
In the patch listing there is the possibility that a file has experienced a change detected as copied or moved.
These file changes also return an optional diff which should be shown, when clicked on a file.

Screencapture:
https://github.com/cytechmobile/radicle-vscode-extension/assets/7912302/01545409-7340-41a7-8f4f-d17e76cb8cd2

**Comment by maninak** [comment]
Related Zulip discussion https://radicle.zulipchat.com/#narrow/stream/380896-integrations

**Comment by maninak** [comment]
**Results:**


### 🚀 Enhancements


- **patch-list:** show diff for copied and moved files of a patch too when available ([#100](https://github.com/cytechmobile/radicle-vscode-extension/issues/100))
- **patch-list:** show path to containing directory for each changed file of a patch ([#100](https://github.com/cytechmobile/radicle-vscode-extension/issues/100))
- **patch-list:** feat(patch-list): increase count of fetched patches per status to 500

### 🔥 Performance

- **patch-list:** speed-up overall list rendering and reduce perf impact when it includes patches with high counts of changed files ([#100](https://github.com/cytechmobile/radicle-vscode-extension/issues/100))
