### ISSUE TITLE
Fix patches view missing items

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#105]
A planned httpd schema change is expected that may break the request to get the list of patches.

https://radicle.zulipchat.com/#narrow/stream/369873-support/topic/fetch.20all.20patches.20in.20one.20req/near/426014014

**Comment by maninak** [comment]
**Results:**

### 🩹 Fixes

- **patch-list:** show all patches again as expected, not only those with status "open". Addresses regression caused due to a breaking change in Radicle HTTP API (httpd) while keeping backwards compatibility for users who haven't yet upgraded to the latest httpd
