### ISSUE TITLE
Co-publish extension on Open VSX Registry 

### ISSUE THREAD

**Issue by GitMensch** [cytechmobile/radicle-vscode-extension#120]
Please add this useful extension to the [Open VSX Registry](https://open-vsx.org/?search=radicle), also helping with the visibility of Radicle.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

A bit of explanation:
Open VSX Registry is the default extension provider endpoint for the free build of vscode VSCodium and Eclipse Theia, as well as browser versions like the one on GitPod. It would be nice to have this extension directly published to a free vsix repository instead of only the Microsoft Marketplace with its restrictions.

Note: You could also use a [GitHub action](https://docs.github.com/en/actions) that allows publishing to Open VSX and the MS market place, [HaaLeo/publish-vscode-extension](https://github.com/HaaLeo/publish-vscode-extension#readme) does this.

**Comment by maninak** [comment]
Co-publishing at Open VSX makes a lot of sense.

Thanks for taking the time for this well-written suggestion, GitMensch!

**Comment by gsaslis** [comment]
I think we should do this with our next release.

**Comment by maninak** [comment]
I was planning to release the current latest one first, to test the waters and then keep publishing both on each release.

Before that, I still need to do some intermediate test releases with the [repository metadata](https://github.com/cytechmobile/radicle-vscode-extension/blob/main/package.json#L17) switched to point to the radicle one, which needs params to resolve how the marketplace website will resolve the radicle-hosted images. This can only be verified by trial (& maybe error), so once a couple 0.4.X releases are out with that stabilized (if possible), then I'd look into Open VSX next.

**Comment by maninak** [comment]
Heads up, the extension is now [co-published as Open VSX Registry](https://open-vsx.org/extension/radicle-ide-plugins-team/radicle)! :tada: :)

In the interest of time, I opted to do that before switching the repository metadata away from GitHub. I've also already applied to get our namespace `radicle-ide-plugins-team` verified, so that should be coming soon too.
