### ISSUE TITLE
chore: `Buffer()` is deprecated

### ISSUE THREAD

**Issue by lorenzleutgeb** [cytechmobile/radicle-vscode-extension#130]
`extensionHostProcess.js` host prints:
```
(node:1324887) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node.patched --trace-deprecation ...` to show where the warning was created)
```

CI fails: https://github.com/cytechmobile/radicle-vscode-extension/actions/runs/8893165652/job/24418860284?pr=128#step:7:23

I did not (knowingly) introduce/use `Buffer()`, and I get the error message on `main` (a669d86f39e65748b5d6f2fce67c5840f3532f2e) too.

I don't know how I can add the argument `--trace-deprecation` to invocation of `node` in order to debug this.

**Comment by lorenzleutgeb** [comment]
OK, tracing works with:

```patch
diff --git a/.vscode/launch.json b/.vscode/launch.json
index 1b1adf8155..37a716a3da 100644
--- a/.vscode/launch.json
+++ b/.vscode/launch.json
@@ -13,6 +13,9 @@
       "outFiles": ["${workspaceFolder}/dist/**/*.js"],
       "preLaunchTask": "npm: dev",
       "postDebugTask": "Terminate All Tasks",
+      "env": {
+        "NODE_OPTIONS": "--trace-deprecation"
+      }
     },
   ]
 }
```

**Comment by lorenzleutgeb** [comment]
With `--trace-deprecation` I was able to trace the warning down to https://github.com/microsoft/live-share/issues/5024. After disabling the extension `ms-vsliveshare.vsliveshare` the warning is gone. But this also means that I cannot reproduce the CI failure locally anymore. Still investigating...

**Comment by lorenzleutgeb** [comment]
I have understood that the failures are not related apart from both referring to `Buffer`. It seems I just have to get `import { Buffer } from 'node:buffer'` to work.

**Comment by lorenzleutgeb** [comment]
Typing support for `'node:buffer'` was added rather recently: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68470

Solution:

```sh
$ pnpm update '@types/node'
 WARN  Ignoring broken lockfile at [...]/node_modules/.pnpm: Lockfile [...]/node_modules/.pnpm/lock.yaml not compatible with current pnpm
 WARN  1 deprecated subdependencies found: source-map-resolve@0.6.0
Packages: +466
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 489, reused 436, downloaded 30, added 37, done
node_modules/.pnpm/simple-git-hooks@2.9.0/node_modules/simple-git-hooks: Running postinstall script, done in 43ms
node_modules/.pnpm/vue-demi@0.14.6_vue@3.4.26/node_modules/vue-demi: Running postinstall script, done in 82ms
node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild: Running postinstall script, done in 43ms

dependencies:
+ pinia 2.1.7

devDependencies:
+ @types/node 20.12.7
+ eslint-plugin-tailwindcss 3.14.3

Done in 3.1s
```

**Comment by lorenzleutgeb** [comment]
Leaving this open for now, so that maintainers can check out https://github.com/cytechmobile/radicle-vscode-extension/issues/130#issuecomment-2084965415 and maybe include pull that change. Please close otherwise!

**Comment by maninak** [comment]
**Results:**

### 🏡 Chores

- **dev:** configure "Develop Extension" launch configuration to show the stack trace in case of nodejs deprecation warning, helping pinpoint the root cause
