### ISSUE TITLE
Progress badge on radicle icon in Activity Bar while loading

### ISSUE THREAD

**Issue by maninak** [cytechmobile/radicle-vscode-extension#15]
![image](https://user-images.githubusercontent.com/7542054/223463841-e679d00b-f35e-40e8-9033-492108a0ebe8.png)
![image](https://user-images.githubusercontent.com/7542054/223460124-2bfaead4-d726-4369-a5f7-8a61db500944.png)

**Resources:**

- https://code.visualstudio.com/api/ux-guidelines/views#views-with-progress
- https://code.visualstudio.com/api/extension-capabilities/common-capabilities#progress-api
- https://github.com/microsoft/vscode-extension-samples/tree/main/progress-sample

**Comment by maninak** [comment]
Relates to https://github.com/cytechmobile/radicle-vscode-extension/issues/5

**Comment by maninak** [comment]
FYI this is already implemented in the work done for the new Patches view https://github.com/cytechmobile/radicle-vscode-extension/issues/43#issuecomment-1724566221

![Image](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/4370ecf9-dd01-4164-8c10-d030c8d295ae)

Here's how it actually works behind the scenes:

- reload button needs to be bound to a View and a Command https://github.com/cytechmobile/radicle-vscode-extension/blob/5b22e1c34b7cc63d005c97e4334e8674f1176fb7/package.json#L123
- clicking the button [triggers the command](https://github.com/cytechmobile/radicle-vscode-extension/blob/5b22e1c34b7cc63d005c97e4334e8674f1176fb7/src/helpers/command.ts#L89)
- which [fires an eventEmitter](https://github.com/cytechmobile/radicle-vscode-extension/blob/5b22e1c34b7cc63d005c97e4334e8674f1176fb7/src/ux/patches.ts#L142)
- that triggers the Patches TreeViewProvider to run its [`getChildren(undefined)`](https://github.com/cytechmobile/radicle-vscode-extension/blob/5b22e1c34b7cc63d005c97e4334e8674f1176fb7/src/ux/patches.ts#L96) (according to the docs, when called with `undefined` it's trying to build the children of the treeview root, i.e. all list items) 
- apparently `getChildren()` [automatically uses the Progress API](https://github.com/microsoft/vscode/blob/062ba1ed6c2b9ff4819f4f7dad76de3fde0044ab/src/vs/workbench/browser/parts/views/treeView.ts#L1065) to show that the view is busy
- and because the View is bound to the Activity Bar (a.k.a. sidebar with Radicle logo) the Progress (a.k.a. busy) indicator is shown there automatically too

------

Now this ticket started out more as "let's use this feature" and, as of writing this, has no explicit spec to implement.

I suggest we either move AC No. (3) from https://github.com/cytechmobile/radicle-vscode-extension/issues/5
    ![Image](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/486200e6-d5d0-4dd5-9084-7086b179ea5a)
into this issue description (and delete the "relates to" comments in both tickets). This would also better narrow the scope of #5.

Other alternatives are to just close this ticket as done and create a new one with the moved out AC of #5 or close and not change anything else. (or something else?)

Marking this as needs-refinement and leaving it to @gsaslis for follow-up.

**Comment by gsaslis** [comment]
Closing this as done. #5 is not in the current refinement scope, so we will edit accordingly when we come round to picking up that work (and shouldn't really beforehand). ;)
