### ISSUE TITLE
Dynamically enabled Welcome Views

### ISSUE THREAD

**Issue by maninak** [cytechmobile/radicle-vscode-extension#16]
VS Code API provides the capability to show specific [Welcome Views](https://code.visualstudio.com/api/ux-guidelines/views#welcome-views) inside a [View Container](https://code.visualstudio.com/api/ux-guidelines/views#view-containers) when the default views of that container are empty and specific extension-author-defined [conditions are met](https://code.visualstudio.com/api/references/when-clause-contexts).

This is very powerful! For example we're currently showing this "note" to communicate to the user some preconditions without which the extension will not work as expected

![image](https://user-images.githubusercontent.com/7542054/223468827-e16f039b-543d-42d0-8151-5365ba755b7f.png)

We could instead detect if the user has opened a workspace with a git repo and only show the message to them in that case, instead of showing it to everyone always.

Or have another Welcome View variant when the user has a git repo but hasn't initialized it with the radicle network, where we have specific buttons and text on how to get him started.

More ideas under specific conditions:
 - rad clone button
 - open directory button
 - ...

**Resources:**

- https://code.visualstudio.com/api/references/contribution-points#contributes.viewsContainers
- https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome
- https://code.visualstudio.com/api/references/when-clause-contexts
- https://code.visualstudio.com/api/ux-guidelines/views#welcome-views
- https://code.visualstudio.com/api/ux-guidelines/views#view-containers

**Comment by gsaslis** [comment]
@maninak closing this in favour of #23
