### ISSUE TITLE
Support cloning with radicle project ID from git -> clone

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#27]
From the Git -> Clone action, we want to introduce support for cloning radicle projects when you only have the Radicle project id (which looks like: ` rad:z42Q64chcGUSgcYHmNwG2DTyrSy8H`). 

We should allow the VS Code user to paste the radicle project id in the input field shown in the below screenshot: 

![Image](https://user-images.githubusercontent.com/2420882/228789984-108fe309-9b01-42bd-91c7-c9876fe3b688.png)

## Acceptance tests

* if the path to the radicle binary hasn't been set (or no binary is found in the path) - and I try to clone a radicle project id, I am taken to the settings screen to configure those correctly (or I go through the existing CLI installation troubleshooting flow)
* when extension is installed, I can clone a radicle project that the node I am connected to knows about
* when extension is installed, and the node doesn't know about the project, I am told about that and that perhaps I need to first _track_ a radicle peer that seeds this project
* when extension is not installed, I can't clone the radicle project
  * (thought) is there any way for vs code to tell users that an extension that "supports this protocol" exists?

**Comment by maninak** [comment]
Regarding

- if the path to the radicle binary or **RAD_HOME haven't been set - and I try to clone a radicle project id, I am taken to the settings screen to configure those correctly**

I believe that if the `$RAD_HOME` hasn't been set (as env var) the CLI will automatically use the default `<$HOME>/.radicle`. ([Source](https://radicle.zulipchat.com/#narrow/stream/369277-heartwood/topic/.E2.9C.94.20RAD_HOME.20and.20terminology/near/360967358))

Thus I think that we shouldn't get the user to the settings screen if the env var OR the related extension config are not set.

**Comment by gsaslis** [comment]
@maninak that's correct. I'll edit that accordingly. 👍🏼

**Comment by gsaslis** [comment]
@maninak I believe the desired functionality is now included in the work you’re doing as part of #29 ,  so I’m closing this.
