### ISSUE TITLE
Typo - copy in rad init warning message is off

### ISSUE THREAD

**Issue by bordumb** [cytechmobile/radicle-vscode-extension#30]
## Actual Results

The copy when opening an unitialized directory/repo is odd. 

### Steps to reproduce

* Open a random (uninitialized directory in VSCode)
* Click on Radicle Icon
* Warning message pops up reading:
> The git repository currently opened in your workspace is not yet initialized with Radicle.
>
> To use Radicle, you can run `rad init` in your terminal after ensuring that the Radicle CLI is installed on your machine.
> 
> Once initialized, your repository **will you'll** have access to advanced source control and project management features powered by git and Radicle. 
> 
> For more help, please read the Getting Started Guide.

This section "your repository **will you'll** have access" reads a bit oddly.

## Expected Results

It should read like this:
> The git repository currently opened in your workspace is not yet initialized with Radicle.
>
> To use Radicle, you can run `rad init` in your terminal after ensuring that the Radicle CLI is installed on your machine.
> 
> Once initialized, your repository will have access to advanced source control and project management features powered by git and Radicle. 
> 
> For more help, please read the Getting Started Guide.

Screen recording:
https://user-images.githubusercontent.com/3743841/230437978-68d49417-be27-4a19-9fdd-3e741424a16e.mov

**Comment by maninak** [comment]
Hey @bordumb, thank you so much for taking the time to contribute by reporting this and especially in such a clean way! :bow: 

The fix will go live with the new patch release pretty soon.

**Comment by maninak** [comment]
Published with v0.1.1
