### ISSUE TITLE
End-to-end testing pipeline

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#35]
Resources:

- https://code.visualstudio.com/api/extension-guides/testing
- https://code.visualstudio.com/api/working-with-extensions/testing-extension
- https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-test-sample

![Screenshot 2023-10-25 at 12 00 49 PM](https://github.com/cytechmobile/radicle-vscode-extension/assets/2420882/6f288c6a-8374-4f9e-b6d5-d2a1c4415087)

**Comment by maninak** [comment]
**Results:**

### 🤖 CI

- **e2e:** set up new infrastructure and a related CI workflow capable of automated completely end-to-end testing. It uses a real Radicle node, which powers the latest extension build, which is running in an actual VS Code. Tests can assert behavior and state even as deep as extension webviews.

### ☑️ Tests

- **onboarding:** cover various paths of the flow with e2e tests

**Screenshots:**

![image](https://github.com/user-attachments/assets/094aff1f-8e28-448c-a892-7791f0274240)


Taken from [workflow](https://github.com/cytechmobile/radicle-vscode-extension/actions/runs/12045289909/job/33583650630?pr=158#step:11:32)
