### ISSUE TITLE
Replace pre-heartwood, now deprecated actions

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#42]
We should replace `rad push` and `rad pull` with `sync --announce` and `sync --fetch` correspondingly. 

We can keep the same buttons and simply replace the underlying functionality with rad sync --fetch / rad sync --announce.

This would leave us with 3 separate buttons (fetch, announce, both), to represent the **different actions** (pushing to the network, fetching from the network and 2-way sync). 

Zulip discussion: https://radicle.zulipchat.com/#narrow/stream/380896-ide-plugins/topic/vscode.20support.20-.20rad-push.2Fpull.20not.20found/near/372229420

**Comment by maninak** [comment]
Assigning it to you until the ticket is updated with the latest spec.

**Comment by gsaslis** [comment]
re-assigning

**Comment by maninak** [comment]
**Result:**

https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/4c960dee-8d92-4771-b19b-9e6009cf2307

Readme copy and UI screenshots have also been brought up to date.
