### ISSUE TITLE
Radicle Patch Overview: List of commits

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#45]

**Comment by gsaslis** [comment]
The list of commits can be shown in the activity view, so closing this for now, until we can come up with a concrete reason for having this somewhere separately.

**Comment by maninak** [comment]
@gsaslis If by Activity View you mean the native Source Control plugin of VS Code

![image](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/2b91e85f-2f64-4aaf-aa0d-018322f4aebc)

then it's worth noting that one can only see those commits after a specific Revision of a Patch is checked out.

I think it is reasonable (although I don't expect common) for users to want to explore the commits of different Revisions of a Patch under certain scenarios:

 - figuring out how Radicle and Patch Revisions work
 - proof-checking if they did everything as they think they did (via CLI or GUI)
 - reviewing the evolution of a Patch from recvision to revision
 - ...something else?
