### ISSUE TITLE
Update branding

### ISSUE THREAD

**Issue by maninak** [cytechmobile/radicle-vscode-extension#56]
Radicle has updated its branding, including changing its seedling logo. We must correct the following to align our extension with the new branding.

- update the logo used in the marketplace 
- update the logo used in our dedicated TTF used in buttons, including the Activity Bar, "Clone from Radicle" etc
    - must be monochrome!
- replace sync/push/pull seedling icons everywhere and use [built-in codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html) instead
- [radicle-brand.zip](https://github.com/cytechmobile/radicle-vscode-extension/files/12070219/radicle-brand.zip)

**Comment by gsaslis** [comment]
https://radworks.org/brand

**Comment by maninak** [comment]
**Result:**

- new themed icons were handcrafted (and an associated .woff font containing them, needed in VS Code extensions)
    - ![image](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/43f9be5f-8840-4550-9c20-fbe7aa60645a)
    - 📥 [radicle-alien-icons.zip](https://github.com/cytechmobile/radicle-vscode-extension/files/12184527/radicle-alien-icons.zip)
- all readme screenshots were updated to show the updated, rebranded UI

For more context, it's worth checking the PR itself for a [visual diff](https://github.com/cytechmobile/radicle-vscode-extension/pull/63/files#diff-5dd2eaa4db811c6b5b9a92689e3e7a3a229e35c4cb0d3c325b065cd5feb9e126).
