### ISSUE TITLE
Migrate new-Radicle-identity-creation logic for updated `rad auth` and improve UX

### ISSUE THREAD

**Issue by maninak** [cytechmobile/radicle-vscode-extension#67]
Radicle CLI's command `rad auth` has been updated to always require an alias to be set when initializing a new identity or the error `✗ Authentication failed: The input device is not a TTY` will be shown.

We need to
- [X] ensure that when we run rad auth _to initialize a new identity_ we always append `--alias <userProvidedAlias>`
- [x] show the alias instead of or along with the DID across all instances we currently show the DID
- [x] find out how we should handle existing un-aliased identities and patch that UX appropriately
- [X] ask the user for an alias if we're initializing a new identity
    - [X] suggest using OS username, same as the CLI does
- [x] ask the user twice to type in the passphrase, when creating a new identity, so as to guard against typos
    That's one additional time vs what we do now, and will align us with the CLI's `rad auth` UX
- [x] convert the InputBox to a multi-step variant
    - [X] show the number of the current step in the flow
    - [X] show count of total steps until flow is finished
    - [X] don't show current/total step(s) if flow has only one total step
    - [X] show a button to go back to previous step
    - [X] when clicking back button, pre-populate the input with the already submitted value
    - [X] behave the same if the user cancels (e.g. pressing `Esc`) the flow at any step (currently, we only detect if the latest step was canceled)
- [X] for password inputs show a button that toggles between obfuscated and cleartext input
    - [X] remember clear/obfuscated text state between steps
- [X] allow entering an empty passphrase
    - [X] warn the user that their Radicle key will be unencrypted if they choose an empty passphrase when creating a new identity (align with the CLI's `rad auth` UX)

**Comment by gsaslis** [comment]
>  don't (obviously falsely...) ask the user each time to authenticate before running auth-guarded commands, when their identity was created with an empty passphrase

@maninak I'll move this to a new issue, so we can look into that separately, later.

**Comment by maninak** [comment]
@gsaslis regarding 
`find out how we should handle existing un-aliased identities and patch that UX appropriately`

After thinking about it, I propose we don't handle it. We can accept it as a breaking change (since Radicle is in pre-production and we additionally barely have any users) and not add complexity to our code handling what seems to be an expiring edge case.

Additionally, I don't have such an identity, which I'd need for testing, where I to work on the topic.

If you disagree with the above, please let me know so that I can instead look into it.

**Comment by maninak** [comment]
**Result:**

![image](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/c857279c-b8c0-4553-ba3f-06a1d9811da9)

https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/bfa7bfeb-9055-4a01-9bdc-48b853368846

**Comment by gsaslis** [comment]
> @gsaslis regarding 
> 
> `find out how we should handle existing un-aliased identities and patch that UX appropriately`
> 
> 
> 
> After thinking about it, I propose we don't handle it. We can accept it as a breaking change (since Radicle is in pre-production and we additionally barely have any users) and not add complexity to our code handling what seems to be an expiring edge case. People can add an alias to an existing identity anyway, from what I understand.
> 
> 
> 
> Additionally, I don't have such an identity, which I'd need for testing, where I to work on the topic.
> 
> 
> 
> If you disagree with the above, please let me know so that I can instead look into it.

I fully agree!
