### ISSUE TITLE
Support identities with blank passphrase

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#71]
There is an issue with keys without a passphrase and we need to change our UX (we currently always request a passphrase) to handle that. 

Relevant discussion in: https://radicle.zulipchat.com/#narrow/stream/374620-cli/topic/how.20to.20detect.20identity.20is.20unencrypted/near/386272437

**Comment by maninak** [comment]
**Result:**

https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/2cae18b9-532f-4a9e-a059-cb8a89878f69
