### ISSUE TITLE
Check out Radicle Patch

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#75]
This issue is about adding the "Check out" action to the Radicle Patch, as per the screenshot below: 

![Image](https://github.com/cytechmobile/radicle-vscode-extension/assets/2420882/da2ee264-1024-41b1-8d4e-c88dd695ad52)

The `rad patch checkout $patch_id` command can then be used to actually checkout the (latest revision of the) patch. 

Acceptance tests:

- don't allow checking out if on a working copy with uncommitted/ unstashed changes
- if patch is already checked out and we are on that patch branch already then no need to checkout again (a message might be nice)
- Checking out should clearly inform the user about what happened (branch changed, upstream branch tracked)

**Comment by maninak** [comment]
@gsaslis if you can think of any edge cases that we should handle, meaning ones needing special handling or which may cause an error, please put them in the issue description so that our solution could account for them or at the very least be tested against them.

Thank you!

**Comment by gsaslis** [comment]
Added a couple of points ;)

**Comment by maninak** [comment]
**Results:**

https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/846c8e20-92a2-4af7-abce-672f4fc5a0c4

### 🚀 Enhancements

- **patches:** show a button to check out a Radicle Patch's associated git branch
  - show an indicator on the Patch's title and tooltip if its associated branch is the currently checked-out git branch
  - keep indicator's state in sync even if the git branch change doesn't happen from within our UI (e.g. `rad patch checkout` or `git checkout` in the terminal)
  - notify user of uncommitted changes when trying to check out a Patch
  - don't show check-out-button for the currently checked-out Patch on the list

### 🔥 Performance

- **app:** heavily speed up most procedures by memoizing the resolution of the reference to the rad CLI
- **patches:** heavily speed up (re-)loading of Patches list
  - measured ~50x faster against a real-world Project with >50 Patches, with the benefit increasing proportionally with the count of Patches on a project

### 🩹 Fixes

- **patches:** fall back to showing their DID if the revision author's alias isn't defined 
- **patches:** use new better-fitting icon for merged Patches 
- **patches:** improved the contrast of the colors used by Patch status icons for light themes 

### 📖 Documentation

- **contributing:** document how to package locally from source and import into VS Code
- fix some screenshots that were getting stretched to incorrect ratios
