### ISSUE TITLE
Support changing a patch's status

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#87]
On the Patch overview page, the maintainer / contributor need to be able to _archive_ a specific patch that they no longer wish to merge.

In full we need to support the following operations on a patch:
- archiving (from open)
- un-archiving (to open)
- moving to draft (from open)
- moving back from draft (to open)

**Comment by maninak** [comment]
**Results:**


https://github.com/user-attachments/assets/f342df4b-c656-4bab-bd9d-70456b45d462


https://github.com/user-attachments/assets/f02db7a6-99ca-4a84-9a13-8762979560c3





### 🚀 Enhancements

- **patch-list:** support changing a patch's status via new context-menu (right-click) actions "Change Patch Status to Draft[or Open/Archived]" on non-merged patch items
  - only shown if the user is authorized to perform the actions
  - only those actions applicable given the patch's status are shown
- **patch-detail:** support changing a patch's status via a new button "Edit"
  - shown on hover or on keyboard-focus of the patch status badge. The button replaces the badge in place, with visual cues assisting the transition.
  - only shown if the user is authorized to perform the actions
  - clicking the Edit button toggles the visibility of status selection radio buttons and becomes "Close" while they are visible
  - selecting a status from the available radios will immediately trigger a patch status change. The handling of this command supports the rich UX also described above for the title and description change.
  - keyboard focus is preserved on the button after pressing "clicking" it with the keyboard, even though there are four different elements conditionally layered on top of each other, including two separate buttons
  - this bespoke Edit toggle button(s) still behaves like the standard one e.g. showing a focus ring but only when focused with the keyboard remaining accessible *and* visually lean
  
### 🔥 Performance

- **patch-list:** speed up (re-)loading of Patches view by caching env state previously resolved anew for each patch item in the list
  - measured as ~25% faster for a real-world Project with >350 patches
