### ISSUE TITLE
Source Control Panel with new Push/Pull/Sync buttons

### ISSUE THREAD

**Issue by maninak** [cytechmobile/radicle-vscode-extension#9]
Next to commit button, or as part of some submenu shown in the radicle interactive prototypes, here https://www.figma.com/proto/9h2suLnyckUXGmMyReMiYP/LF-Wireframe---Milestone-1?node-id=472684%3A9231&scaling=contain&page-id=77%3A432&starting-point-node-id=472684%3A9231&show-proto-sidebar=1

Notes:

`rad push` == `git push rad && rad sync`

As such, we want to consider if it's possible for this action to invoke the **native** VS Code git push and THEN, once git push is completed, to invoke rad sync. (this is what we do in intellij - if not possible, we can just delegate to rad sync on the commandline)

**Resources:**

- Relevant [discussion](https://github.com/cytechmobile/radicle-jetbrains-plugin/issues/8) in intellij plugin as some questions may be relevant here too

**Comment by maninak** [comment]
**Result:**

https://user-images.githubusercontent.com/7542054/225074176-0f03486d-9aca-4e92-ac3a-e4d4a37f96a7.mp4

Turns out we can not only create our own Submenu as an entry to the 3dot-menu of Source Control View, but we can also add commands-as-buttons in the View's "navigation" bar. Moreover, we can have such a button open our own Radicle Submenu. Or even append entries to existing Submenues of the 3dot-menu of SCV.

Food for thought... :wink: CC @gsaslis 

What is missing is making all those extra UI elements context-aware, so that they are shown only under certain conditions.

**Comment by gsaslis** [comment]
> Turns out we can not only create our own Submenu as an entry to the 3dot-menu of Source Control View, but we can also add commands-as-buttons in the View's "navigation" bar. Moreover, we can have such a button open our own Radicle Submenu. Or even append entries to existing Submenues of the 3dot-menu of SCV.

as a more experienced vscode user than myself, which approach feels more natural to you?

> What is missing is making all those extra UI elements context-aware, so that they are shown only under certain conditions.

see #23 re: context

**Comment by maninak** [comment]
> as a more experienced vscode user than myself, which approach feels more natural to you?

I created my proposal as a new ticket (#24).

If you like it as is, please move it to "Remaining for v0.1.0". Otherwise feel free to make any edits as needed, or ping me on Zulip to discuss.

**Comment by bordumb** [comment]
Started reviewing the closed PRs for the milestone delivery.

These screen recordings in all the PRs are awesome! :D
